mail:
  tls: true
  address: smtp.gmail.com
  port: 587
  domain: sigeol.com
  authentication: plain
  user_name: quixoft.sol@gmail.com
  password: sigeol08
  host: www.sigeol.it

servlet:
  address: http://localhost:8080/middleman/scheduler.do
  timeout: 300